project:
  type: website
  pre-render:
    - site-attachments/packages.R
    - site-attachments/purl-r-scripts.R
  post-render:
    - site-attachments/create-example-folder.R
  render: 
    - "*.qmd"
    - "!ignored-dir/"
    - "!site-attachments/quarto-template.qmd"
    - "!/site-attachments/assignments/"
    - "!EDH-7916/"
  resources:
    - "archive/spring-2024.zip"
    
website:
  title: "EDH 7645"
  site-url: "https://juewu-wj.github.io/7645"
  description: "Course website for EDH 7645 at the University of Florida"
  image: "apple-touch-icon.png"
  favicon: "apple-touch-icon.png"
  twitter-card: true
  open-graph: true
  navbar: false
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - text: "Syllabus"
        file: "syllabus.qmd"
      - section: "Getting Started"
        contents: "*set*" # glob search for files with Setup
      - section: "Data Wrangling"
        contents: "*wrangle*"
      - section: "Data Visualization"
        contents: "*viz*"
      - text: "Reproducible Reports with Quarto"
        file: "07-quarto-intro.qmd"
      - text: "Functions & Loops"
        file: "11-pro-functions.qmd"
      - text: "Bringing it All Together (Feat. Basic Models)"
        file: "12-pro-model.qmd"
      - text: "Final Project"
        file: "99-final.qmd"
      - section: "Extra Credit"
        contents: "*x-*"
    collapse-level: 1

  page-footer:
    right: 
      - text: "Built with Quarto"
        href: https://quarto.org/docs/websites
      - icon: github
        aria-label: Website Code Available Here
        href: https://github.com/juewu-wj/7645
    left:
      - text: "Jue Wu"
        href: https://juewu-wj.github.io/

      
format:
  html:
    theme: simplex
    css: site-attachments/styles.css
    toc: false
    email-obfuscation: references
    anchor-sections: false

editor: source

